---
- name: Setup MySQL Database
  hosts: all
  become: yes
  tasks:

    - name: Install MySQL server
      apt:
        name: mysql-server
        state: present
        update_cache: yes

    - name: Install Python MySQL driver
      apt:
        name: python3-mysqldb
        state: present
        update_cache: yes

    - name: Start MySQL service
      service:
        name: mysql
        state: started
        enabled: true

    - name: Create MySQL database
      mysql_db:
        name: example_db
        state: present
        login_user: root
        login_password: "Albasha!1303Pass"  # Ersetze mit deinem tatsächlichen Passwort

    - name: Create MySQL user
      mysql_user:
        name: wp_user
        password: albasha!Passwort123
        priv: 'example_db.*:ALL'
        host: localhost
        state: present
        login_user: root
        login_password: "Albasha!1303Pass"  # Ersetze durch dein tatsächliches Passwort
        
    - name: Flush MySQL privileges
      mysql_query:
        query: "FLUSH PRIVILEGES;"
        login_user: root
        login_password: "Albasha!1303Pass"  # Ersetze durch dein tatsächliches Passwort






